name: Build and run heimdall_tools

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-16.04, ubuntu-latest, macos-latest, windows-latest]
        ruby: [ 2.4, 2.5, 2.6, 2.7 ]
        # TODO: Remove this exclusion once Nokogiri is supported on ruby 2.7 for Windows
        exclude:
          - platform: windows-latest
            ruby: 2.7
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Test on Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build gem and run it
        run: |
          gem install bundler
          bundle install
          gem build heimdall_tools.gemspec
          gem install heimdall_tools-*.gem
          heimdall_tools help
          heimdall_tools version
